version: "3.8"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./devops/config/nginx-api.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/var/www/api
      - ./devops/local/config/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./devops/local/config/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
      - redis

  mysql:
    build:
      args:
        password: password
      context: .
      dockerfile: devops/local/Dockerfiles/Dockerfile.mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ../redisdata:/data
    ports:
      - "6379:6379"

  scheduler:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: api/Dockerfile
      target: scheduler
    restart: unless-stopped
    depends_on:
      - update
      - mysql
      - redis

  worker:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: api/Dockerfile
      target: worker
    restart: unless-stopped
    depends_on:
      - update
      - mysql
      - redis

  update:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: api/Dockerfile
    command: sh -c "./bin/wait-for-it.sh mysql:3306 -t 30 && ./bin/update.sh"
    restart: no
    volumes:
      - ./api/composer.json:/var/www/api/composer.json
      - ./api/composer.lock:/var/www/api/composer.lock
#      - ./devops/local/envs/api.env:var/www/api/.env
      - ./devops/local/bin/update.sh:/var/www/api/update.sh
    depends_on:
      - mysql

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'