FROM node:18.0.0-alpine AS base
WORKDIR /var/www/frontend

COPY ../../../frontend/package.* .
RUN npm install
COPY ../../../frontend/* ./

FROM base AS dev
EXPOSE 80
CMD ["npm", "run", "serve"]

FROM base AS build
RUN npm run build

FROM base AS prod
COPY --from=build /var/www/frontend/dist /usr/share/nginx/html
COPY ../config/nginx-frontend.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]