version: "3.8"

services:

  proxy:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.proxy
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
#      - frontend
      - nginx

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.nginx
    restart: unless-stopped
    volumes:
      - ../../api:var/www/api
    depends_on:
      - api

  api:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: ../../api/Dockerfile
      target: api
    command: sh -c "./bin/wait-for-it.sh mysql:3306 -t 30 && ./bin/wait-for-it.sh redis:6379 -t 30 && php-fpm"
    restart: unless-stopped
    volumes:
      - ./envs/api.env:var/www/api/.env
      - ./config/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - update
      - mysql
      - redis

  #frontend:
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfiles/Dockerfile.frontend
  #    target: dev
  #  restart: unless-stopped
  #  volumes:
  #    - ../../frontend:/var/www/frontend
  #  environment:
  #    - NODE_ENV=local

  mysql:
    build:
      args:
        password: password
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.mysql
    restart: unless-stopped
    volumes:
      - ../mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ../redisdata:/data
    ports:
      - "6379:6379"

  scheduler:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: ../../api/Dockerfile
      target: scheduler
    restart: unless-stopped
    depends_on:
      - update
      - mysql
      - redis

  worker:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: ../../api/Dockerfile
      target: worker
    restart: unless-stopped
    depends_on:
      - update
      - mysql
      - redis

  update:
    build:
      args:
        user: sami
        uid: 1000
      context: .
      dockerfile: ../../api/Dockerfile
    command: sh -c "./bin/wait-for-it.sh mysql:3306 -t 30 && ./bin/update.sh"
    restart: no
    volumes:
      - ../../api/composer.json:/var/www/api/composer.json
      - ../../api/composer.lock:/var/www/api/composer.lock
      - ./envs/api.env:var/www/api/.env
      - ./bin/update.sh:/var/www/api/update.sh
    depends_on:
      - mysql

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
