name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: api/vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
<<<<<<< HEAD
    - uses: shivammathur/setup-php@v3
=======
      uses: shivammathur/setup-php@v3
>>>>>>> f4850a9 (update)
      with:
        php-version: 8.1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Pest suite
      run: ./vendor/bin/phpstan analyse

    - name: Run Pint suite
      run: ./vendor/bin/pint

    - name: Run Test suite
      run: php artisan test
